### ISSUE TITLE
Tracking for v0.3.0

### ISSUE THREAD

**Issue by ubnt-intrepid** [ubnt-intrepid/rust-gurobi#13]
- [ ] Add missing APIs (#17)
- [ ] Support for callback function (#9)
- [ ] Implement `Copy` trait for each proxy (#16)
